[app]
    segment_duration = 5
    translate_parallel_num = 5

[server]
    host = "127.0.0.1"
    port = 8888

[openai]
    api_key = "sk-XXX"

[aliyun]
    access_key_id = ""
    access_key_secret = ""
    app_key = ""
    cosy_voice_ws_addr = ""