[app]
    segment_duration = 5 # 音频分割间隔，单位：分钟
    translate_parallel_num = 5 # 并发进行大模型翻译的数量上限
    proxy = "" # 网络代理

[server]
    host = "127.0.0.1"
    port = 8888

[openai]
    api_key = "sk-XXX" # OpenAI API密钥

[aliyun] # 此处配置可以先忽略
    access_key_id = ""
    access_key_secret = ""
    app_key = ""
    cosy_voice_ws_addr = ""